version: "3"
services:
  client:
    build:
      context: "./client"
      dockerfile: "dev.Dockerfile"
    restart: "always"
    environment:
      NODE_ENV: "development"
      REACT_APP_PORT: 3000
      REACT_APP_HOST: "0.0.0.0"
      REACT_APP_API_HOST: "0.0.0.0"
      REACT_APP_API_PORT: 3001
    ports:
      - "3000:3000"
    depends_on:
      - "server"
    networks:
      - "react-stories-development-network"
    volumes:
      - "./client:/usr/src/app"
  server:
    build:
      context: "./server"
      dockerfile: "dev.Dockerfile"
    restart: "always"
    environment:
      NODE_ENV: "development"
      NODE_PORT: 3001
      NODE_HOST: "0.0.0.0"
    ports:
      - "3001:3001"
    networks:
      - "react-stories-development-network"
    volumes:
      - ./server/src:/usr/src/app/src

networks:
  react-stories-development-network:
    driver: "bridge"
