version: "3"
services:
  client:
    stdin_open: true
    build:
      context: "./client"
      dockerfile: "dev.Dockerfile"
    restart: "always"
    environment:
      NODE_ENV: "development"
      REACT_APP_PORT: 3000
      REACT_APP_HOST: "0.0.0.0"
      REACT_APP_API_HOST: "0.0.0.0"
      REACT_APP_API_PORT: 3001
    ports:
      - "3000:3000"
    networks:
      - "react-stories-development-network"
    volumes:
      - "./client:/usr/src/app"
networks:
  react-stories-development-network:
    driver: "bridge"