version: "3"
services:
  client:
    container_name: "react-stories-production-client"
    build:
      context: "./client"
      dockerfile: "Dockerfile"
    restart: "always"
    environment:
      NODE_ENV: "production"
      REACT_APP_PORT: 80
      REACT_APP_HOST: "0.0.0.0"
      REACT_APP_API_HOST: "0.0.0.0"
      REACT_APP_API_PORT: 3001
    ports:
      - "3000:80"
    networks:
      - "react-stories-production-network"
networks:
  react-stories-production-network:
    driver: "bridge"
